/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stamps;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Magda
 */
public class UpdateWindow extends javax.swing.JFrame {

    private Stamp stampAfterUpdate = new Stamp();
    private Stamp stampBeforeUpdate = new Stamp();
    private MainWindow mainWindow;
    
    public UpdateWindow(MainWindow main) {
        initComponents();
        populateComponents();
        mainWindow = main;
    }

    //fill in components in pop-up window by corresponding values of choosen record
    public void populateComponents() {
        this.stampBeforeUpdate = Database.getSelectedStampValues();
        Calendar cal = new GregorianCalendar();
        cal.setTime(stampBeforeUpdate.getReleaseDate());
        
        jTextField_Nr.setText(Integer.toString(stampBeforeUpdate.getCatalogNr()));
        jTextField_Name.setText(stampBeforeUpdate.getName());
        jTextField_Unit.setText(stampBeforeUpdate.getUnit());
        jComboBox_Month.setSelectedIndex(cal.get(Calendar.MONTH));
        jComboBox_Day.setSelectedIndex(cal.get(Calendar.DAY_OF_MONTH)-1);       
        jTextField_Year.setText(Integer.toString(cal.get(Calendar.YEAR)));
        jTextField_Production.setText(Long.toString(stampBeforeUpdate.getProduction()));
        jCheckBox_InCollection.setSelected(stampBeforeUpdate.getInCollection());
        jCheckBox_IsStamped.setSelected(stampBeforeUpdate.getStamped());
        
    }
    
    //update record in database
    private void updateRecord() throws SQLException, FileNotFoundException{    
        int day = jComboBox_Day.getSelectedIndex()+1;
        int month = jComboBox_Month.getSelectedIndex()+1;
        int year = Integer.parseInt(jTextField_Year.getText());
             
        stampAfterUpdate.setCatalogNr(Integer.parseInt(jTextField_Nr.getText()));
        stampAfterUpdate.setName(jTextField_Name.getText());
        stampAfterUpdate.setUnit(jTextField_Unit.getText());
        stampAfterUpdate.setReleaseDate(day, month, year);     
        stampAfterUpdate.setProduction(Long.parseLong(jTextField_Production.getText()));
        stampAfterUpdate.setInCollection(jCheckBox_InCollection.isSelected());
        stampAfterUpdate.setStamped(jCheckBox_IsStamped.isSelected());
                            
        try {
            Database.updateRecord(stampBeforeUpdate, stampAfterUpdate);
            JOptionPane.showMessageDialog(null, "Updated data successfully!");
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Unsucessfull to update data.");
            ex.printStackTrace();   
        }  
        mainWindow.refreshJTable();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Name = new javax.swing.JTextField();
        jTextField_Production = new javax.swing.JTextField();
        jLabel_Unit = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jComboBox_Month = new javax.swing.JComboBox();
        jLabel_Nr = new javax.swing.JLabel();
        jComboBox_Day = new javax.swing.JComboBox();
        jTextField_Nr = new javax.swing.JTextField();
        jTextField_Year = new javax.swing.JTextField();
        jButton_ChoosePhoto = new javax.swing.JButton();
        jLabel_PhotoPath = new javax.swing.JLabel();
        jLabel6_Production = new javax.swing.JLabel();
        jLabel_ReleaseDate = new javax.swing.JLabel();
        jCheckBox_InCollection = new javax.swing.JCheckBox();
        jLabel_inCollection = new javax.swing.JLabel();
        jLabel_IsStamped = new javax.swing.JLabel();
        jCheckBox_IsStamped = new javax.swing.JCheckBox();
        jButton_UpdateRecord = new javax.swing.JButton();
        jTextField_Unit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Unit.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_Unit.setText("Unit:");

        jLabel_Name.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_Name.setText("Name:");

        jComboBox_Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MonthActionPerformed(evt);
            }
        });

        jLabel_Nr.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_Nr.setText("Catalog number:");

        jComboBox_Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBox_Day.setEnabled(false);

        jTextField_Year.setToolTipText("year, e.g.: 1982");

        jButton_ChoosePhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamps/folderIcon.png"))); // NOI18N
        jButton_ChoosePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChoosePhotoActionPerformed(evt);
            }
        });

        jLabel_PhotoPath.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_PhotoPath.setText("Change photo:");

        jLabel6_Production.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel6_Production.setText("Production:");

        jLabel_ReleaseDate.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_ReleaseDate.setText("Release date:");

        jCheckBox_InCollection.setText("Yes");
        jCheckBox_InCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_InCollectionActionPerformed(evt);
            }
        });

        jLabel_inCollection.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_inCollection.setText("Have you got this stamp in collection?");

        jLabel_IsStamped.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel_IsStamped.setText("Is stamped?");

        jCheckBox_IsStamped.setText("Yes");

        jButton_UpdateRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamps/updateIcon.png"))); // NOI18N
        jButton_UpdateRecord.setText("UPDATE");
        jButton_UpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nr, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_PhotoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ChoosePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel_ReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jComboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_Year))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel_IsStamped, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_IsStamped))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel_inCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_InCollection))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6_Production, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_Production, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_UpdateRecord))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nr)
                    .addComponent(jTextField_Nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_ChoosePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_PhotoPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Name)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Unit)
                    .addComponent(jTextField_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ReleaseDate)
                    .addComponent(jTextField_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6_Production)
                    .addComponent(jTextField_Production, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inCollection)
                    .addComponent(jCheckBox_InCollection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IsStamped)
                    .addComponent(jCheckBox_IsStamped))
                .addGap(18, 18, 18)
                .addComponent(jButton_UpdateRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MonthActionPerformed
        int[] months31Days = {0, 2, 4, 6, 7, 9, 11};
        int[] months30Days = {3, 5, 8, 10};

        jComboBox_Day.setEnabled(rootPaneCheckingEnabled);

        if (jComboBox_Month.getSelectedIndex() == 1) {  //to do: set 29day to February for proper years
            if (jComboBox_Day.getItemCount() == 30) {
                jComboBox_Day.removeItemAt(jComboBox_Day.getItemCount()-1);
                jComboBox_Day.removeItemAt(jComboBox_Day.getItemCount()-1);
            }
            if (jComboBox_Day.getItemCount() == 31) {
                jComboBox_Day.removeItemAt(jComboBox_Day.getItemCount()-1);
                jComboBox_Day.removeItemAt(jComboBox_Day.getItemCount()-1);
                jComboBox_Day.removeItemAt(jComboBox_Day.getItemCount()-1);
            }
        }
        else {
            for (int element : months31Days) {
                if (jComboBox_Month.getSelectedIndex() == element) {
                    if (jComboBox_Day.getItemCount() == 30)
                    jComboBox_Day.addItem(31);
                    if (jComboBox_Day.getItemCount() == 28) {
                        jComboBox_Day.addItem(29);
                        jComboBox_Day.addItem(30);
                        jComboBox_Day.addItem(31);
                    }
                }
            }
            for (int element2: months30Days) {
                if (jComboBox_Month.getSelectedIndex() == element2) {
                    if (jComboBox_Day.getItemCount() == 31)
                    jComboBox_Day.removeItemAt(jComboBox_Day.getItemCount()-1);
                    if (jComboBox_Day.getItemCount() == 28) {
                        jComboBox_Day.addItem(29);
                        jComboBox_Day.addItem(30);
                    }
                }
            }
        }
    }//GEN-LAST:event_jComboBox_MonthActionPerformed

    private void jButton_ChoosePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChoosePhotoActionPerformed
        JFileChooser fc = new JFileChooser();
        int rVal = fc.showOpenDialog(UpdateWindow.this);

        if (rVal == JFileChooser.APPROVE_OPTION) {
            String path = fc.getCurrentDirectory().toString()+ "\\" +fc.getSelectedFile().getName();
            File image = new File(path);
            stampAfterUpdate.setPhotoFile(image);
        }
    }//GEN-LAST:event_jButton_ChoosePhotoActionPerformed

    private void jCheckBox_InCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_InCollectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_InCollectionActionPerformed

    private void jButton_UpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateRecordActionPerformed
        try {
            updateRecord();
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_UpdateRecordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ChoosePhoto;
    private javax.swing.JButton jButton_UpdateRecord;
    private javax.swing.JCheckBox jCheckBox_InCollection;
    private javax.swing.JCheckBox jCheckBox_IsStamped;
    private javax.swing.JComboBox jComboBox_Day;
    private javax.swing.JComboBox jComboBox_Month;
    private javax.swing.JLabel jLabel6_Production;
    private javax.swing.JLabel jLabel_IsStamped;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Nr;
    private javax.swing.JLabel jLabel_PhotoPath;
    private javax.swing.JLabel jLabel_ReleaseDate;
    private javax.swing.JLabel jLabel_Unit;
    private javax.swing.JLabel jLabel_inCollection;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Nr;
    private javax.swing.JTextField jTextField_Production;
    private javax.swing.JTextField jTextField_Unit;
    private javax.swing.JTextField jTextField_Year;
    // End of variables declaration//GEN-END:variables
}
